### PR TITLE
Add install script to install from pip for ea3

### PR DESCRIPTION
**Pull request by ssk2**

### CODE REVIEW

**Comment by jsancio** [comment]
Let's not do this against `install-dcos.cli-ea3.sh`. Let's do it against `install-dcos-cli.sh`. Once we start publishing this file we can delete all of the other files.

**Comment by ssk2** [comment]
Yessir. It's not ready to merge yet.

**Comment by ssk2** [comment]
TODO: Update TeamCity build.

**Comment by jsancio** [comment]
LGTM!

**Pull request merged**
